config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  resources :restaurants do
    resources :menu_items, except: [:index, :show]
  end
  resources :employees

  resource :random_lunch, only: [:new]
  post '/random_lunch', to: 'random_lunches#search'
  get '/random_lunch/employee', to: 'random_lunches#employee'
  post '/random_lunch/employee', to: 'random_lunches#employee_search'

  resource :paid_lunch, only: [:new]
  post '/paid_lunch', to: 'paid_lunches#search'
  get '/paid_lunch/employee', to: 'paid_lunches#employee'
  post '/paid_lunch/employee', to: 'paid_lunches#employee_search'

  resources :user_sessions, only: [:create]
  delete '/logout', to: 'user_sessions#destroy', as: 'logout'
  get '/login', to: 'user_sessions#new', as: 'login'

  root 'welcome#index'
end

app/controllers/random_lunches_controller.rb
# frozen_string_literal: true

class RandomLunchesController < ApplicationController
  before_action :require_login

  def new
    @tags = Tag.all
  end

  def search
    @restaurants = RandomLunchQuery.new(params).call

    render 'search'
  end

  def employee
    @employees = Employee.all
    @tags = Tag.all
  end

  def employee_search
    @restaurants = RandomLunchQuery.new(params).call

    render 'employee_search'
  end
end

app/views/random_lunches/_results.html.haml
%h2.title.is-4 Results

- if restaurants.any?

  .content
    %ul
      - restaurants.each do |restaurant|
        %li
          = link_to restaurant.name, restaurant

- else

  %article.message.is-large
    .message-body
      No restaurants matched.

app/views/random_lunches/employee.html.haml
%h1.title Random Lunch

- if @employees.any?

  .content
    %p
      Please select preferences for employees having lunch:

  = form_with url: random_lunch_employee_path, local: true do |form|

    - @employees.each do |employee|

      .field.is-horizontal
        .field-label.is-normal
          %label.label= employee.name
        .field-body
          .field
            .control
              .select
                %select{ name: "tag_ids[]" }
                  %option{ value: "" }= t('lunch.not_eating')
                  = options_from_collection_for_select(@tags, :id, :name)

    .field.is-horizontal
      .field-label
      .field-body
        .field
          .control
            = form.submit "Search", class: 'button is-primary'

- else

  %article.message.is-large
    .message-body
      No employees found. Go to
      = link_to "Manage Employees", employees_path

app/views/random_lunches/employee_search.html.haml
%h1.title Random Lunch

.field
  = link_to 'New search', random_lunch_employee_path, class: "button is-link"

= render "results", restaurants: @restaurants

app/views/random_lunches/new.html.haml
%h1.title Random Lunch

= form_with url: random_lunch_path, local: true do |form|
  .field.is-horizontal
    .field-label.is-normal
      = form.label :tags, "Preferences", class: 'label'
    .field-body
      .field
        .control
          = form.collection_check_boxes :tag_ids, @tags, :id, :name do |b|
            = b.label(class: "checkbox") { b.check_box + "\n" + b.text }
            %br

  .field.is-horizontal
    .field-label
    .field-body
      .field
        .control
          = form.submit "Search", class: 'button is-primary'

app/views/random_lunches/search.html.haml
%h1.title Random Lunch

.field
  = link_to 'New search', new_random_lunch_path, class: "button is-link"

%h2.title.is-4 Results

.content
  %ul
    - @restaurants.each do |restaurant|
      %li
        = link_to restaurant.name, restaurant