config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  resources :restaurants do
    resources :menu_items, except: [:index, :show]
  end
  resources :employees

  resource :random_lunch, only: [:new]
  post '/random_lunch', to: 'random_lunches#search'
  get '/random_lunch/employee', to: 'random_lunches#employee'
  post '/random_lunch/employee', to: 'random_lunches#employee_search'

  resource :paid_lunch, only: [:new]
  post '/paid_lunch', to: 'paid_lunches#search'
  get '/paid_lunch/employee', to: 'paid_lunches#employee'
  post '/paid_lunch/employee', to: 'paid_lunches#employee_search'

  resources :user_sessions, only: [:create]
  delete '/logout', to: 'user_sessions#destroy', as: 'logout'
  get '/login', to: 'user_sessions#new', as: 'login'

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  before_action :require_login

  def index
  end
end

app/views/welcome/_tile.html.haml
.tile.is-parent
  .box.tile.is-child
    %article.media
      .media-left
        %span.icon.is-large
          %i.fas.fa-lg{ class: icon }
      .media-content
        .content
          %p.title.is-4
            = link_to title, path

app/views/welcome/index.html.haml
%h1.title.is-1 Administration

.tile.is-ancestor
  .tile.is-12
    = render partial: 'tile', locals: { title: "Manage Restaurants and Menu Items", path: restaurants_path, icon: "fa-utensils" }

    = render partial: 'tile', locals: { title: "Manage Employees", path: employees_path, icon: "fa-users" }

.tile.is-ancestor
  .tile.is-12
    = render partial: 'tile', locals: { title: "Random Lunch (Simple)", path: new_random_lunch_path, icon: "fa-dice"}
    = render partial: 'tile', locals: { title: "Random Lunch with Employees", path: random_lunch_employee_path, icon: "fa-dice" }

.tile.is-ancestor
  .tile.is-12
    = render partial: 'tile', locals: { title: "Paid Lunch (Simple)", path: new_paid_lunch_path, icon: "fa-search-dollar" }
    = render partial: 'tile', locals: { title: "Paid Lunch with Employees", path: paid_lunch_employee_path, icon: "fa-search-dollar" }