config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  resources :restaurants do
    resources :menu_items, except: [:index, :show]
  end
  resources :employees

  resource :random_lunch, only: [:new]
  post '/random_lunch', to: 'random_lunches#search'
  get '/random_lunch/employee', to: 'random_lunches#employee'
  post '/random_lunch/employee', to: 'random_lunches#employee_search'

  resource :paid_lunch, only: [:new]
  post '/paid_lunch', to: 'paid_lunches#search'
  get '/paid_lunch/employee', to: 'paid_lunches#employee'
  post '/paid_lunch/employee', to: 'paid_lunches#employee_search'

  resources :user_sessions, only: [:create]
  delete '/logout', to: 'user_sessions#destroy', as: 'logout'
  get '/login', to: 'user_sessions#new', as: 'login'

  root 'welcome#index'
end

app/controllers/paid_lunches_controller.rb
# frozen_string_literal: true

class PaidLunchesController < ApplicationController
  before_action :require_login

  def new
    @tags = Tag.all
  end

  def search
    @budget = budget
    @tag_quantities = tag_quantities

    paid_lunch_query = PaidLunchQuery.new(
      budget: @budget,
      tag_quantities: @tag_quantities
    )
    @restaurants = paid_lunch_query.call

    render 'search'
  end

  def employee
    @employees = Employee.all
    @tags = Tag.all
  end

  def employee_search
    @budget = budget
    @tag_quantities = tag_ids_to_quantities

    paid_lunch_query = PaidLunchQuery.new(
      budget: @budget,
      tag_quantities: @tag_quantities
    )
    @restaurants = paid_lunch_query.call

    render 'employee_search'
  end

  private

  def search_params
    params.permit(:budget, tag_ids: [], tag_quantities: {})
  end

  def budget
    Money.from_amount(search_params[:budget].to_f)
  end

  def tag_quantities
    search_params[:tag_quantities].to_hash.reduce({}) do |h, (k, v)|
      value = v.to_i
      h[k] = value if value.positive?
      h
    end
  end

  def tag_ids_to_quantities
    search_params[:tag_ids].reduce({}) do |h, tid|
      if tid.present?
        h.member?(tid) ? h[tid] += 1 : h[tid] = 1
      end

      h
    end
  end
end

app/views/paid_lunches/_results.html.haml
%h2.title.is-4 Results

- if restaurants.any?

  .content
    %ul
      - restaurants.each do |restaurant|
        %li
          = link_to restaurant.name, restaurant
          %ul
            - tag_quantities.each do |tid, quantity|
              %li
                = quantity
                x
                - menu_item = restaurant.cheapest_menu_item_by(tid)
                = menu_item.name
                = menu_item.price.format(with_currency: true)

- else

  %article.message.is-large
    .message-body
      No restaurants matched.

app/views/paid_lunches/employee.html.haml
%h1.title Paid Lunch

- if @employees.any?

  = form_with url: paid_lunch_employee_path, local: true do |form|
    .field.is-horizontal
      .field-label.is-normal
        = form.label :budget, t('paid_lunch.budget'), class: 'label'
      .field-body
        .field.has-addons
          .control
            %a.button.is-static
              = Money.default_currency.symbol
          .control
            = form.text_field :budget, class: 'input', value: "100.00"

    .content
      %p
        Please select preferences for employees having lunch:

    - @employees.each do |employee|

      .field.is-horizontal
        .field-label.is-normal
          %label.label= employee.name
        .field-body
          .field
            .control
              .select
                %select{ name: "tag_ids[]" }
                  %option{ value: "" }= t('lunch.not_eating')
                  = options_from_collection_for_select(@tags, :id, :name)

    .field.is-horizontal
      .field-label
      .field-body
        .field
          .control
            = form.submit "Search", class: 'button is-primary'

- else

  %article.message.is-large
    .message-body
      No employees found. Go to
      = link_to "Manage Employees", employees_path

app/views/paid_lunches/employee_search.html.haml
%h1.title Paid Lunch

.field
  = link_to 'New search', paid_lunch_employee_path, class: "button is-link"

.content
  %dl
    %dt= t('paid_lunch.budget')
    %dd= @budget.format

= render "results", restaurants: @restaurants, tag_quantities: @tag_quantities

app/views/paid_lunches/new.html.haml
%h1.title Paid Lunch

= form_with url: paid_lunch_path, local: true do |form|
  .field.is-horizontal
    .field-label.is-normal
      = form.label :budget, t('paid_lunch.budget'), class: 'label'
    .field-body
      .field.has-addons
        .control
          %a.button.is-static
            = Money.default_currency.symbol
        .control
          = form.text_field :budget, class: 'input', value: "100.00"

  - @tags.each do |tag|
    .field.is-horizontal
      .field-label.is-normal
        = form.label tag.name, class: 'label'
      .field-body
        .field
          .control
            = form.text_field "tag_quantities[#{tag.id}]", class: 'input', value: "0"

  .field.is-horizontal
    .field-label
    .field-body
      .field
        .control
          = form.submit "Search", class: 'button is-primary'

app/views/paid_lunches/search.html.haml
%h1.title Paid Lunch

.field
  = link_to 'New search', new_paid_lunch_path, class: "button is-link"

.content
  %dl
    %dt= t('paid_lunch.budget')
    %dd= @budget.format

%h2.title.is-4 Results

.content
  %ul
    - @restaurants.each do |restaurant|
      %li
        = link_to restaurant.name, restaurant
        %ul
          - @tag_quantities.each do |tid, quantity|
            %li
              = quantity
              x
              - menu_item = restaurant.cheapest_menu_item_by(tid)
              = menu_item.name
              = menu_item.price.format(with_currency: true)