config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  resources :restaurants do
    resources :menu_items, except: [:index, :show]
  end
  resources :employees

  resource :random_lunch, only: [:new]
  post '/random_lunch', to: 'random_lunches#search'
  get '/random_lunch/employee', to: 'random_lunches#employee'
  post '/random_lunch/employee', to: 'random_lunches#employee_search'

  resource :paid_lunch, only: [:new]
  post '/paid_lunch', to: 'paid_lunches#search'
  get '/paid_lunch/employee', to: 'paid_lunches#employee'
  post '/paid_lunch/employee', to: 'paid_lunches#employee_search'

  resources :user_sessions, only: [:create]
  delete '/logout', to: 'user_sessions#destroy', as: 'logout'
  get '/login', to: 'user_sessions#new', as: 'login'

  root 'welcome#index'
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :menu_items, dependent: :delete_all
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :name, presence: true

  def cheapest_menu_item_by(tag_id)
    taggings.find_by(tag_id: tag_id).try(:lowest_item)
  end
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :require_login

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    @menu_items = @restaurant.menu_items
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    flash[:notice] = t('flash.destroy', resource: Restaurant.model_name.human)
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/restaurants/_form.html.haml
= form_with model: @restaurant, local: true do |form|
  - if @restaurant.errors.any?
    %article.message.is-danger
      .message-header
        Error
      .message-body
        = pluralize(@restaurant.errors.count, "error")
        prohibited this restaurant from being saved:
        .content
          %ul
            - @restaurant.errors.full_messages.each do |msg|
              %li= msg

  .field
    = form.label :name, class: 'label'
    .control
      = form.text_field :name, class: 'input'

  .field.is-grouped
    .control
      = form.submit class: 'button is-primary'
    .control
      = link_to 'Back', restaurants_path, class: 'button'

app/views/restaurants/edit.html.haml
%h1.title Edit Restaurant

= render 'form'

app/views/restaurants/index.html.haml
%h1.title Restaurants

.field
  = link_to 'New restaurant', new_restaurant_path, class: "button is-link"

%table.table.is-striped.is-fullwidth
  %thead
    %tr
      %th Name
      %th Actions

  %tbody
    - @restaurants.each do |restaurant|
      %tr
        %td= restaurant.name
        %td
          %p.buttons
            = link_to restaurant, class: "button" do
              %span.icon.is-small
                %i.far.fa-eye
            = link_to edit_restaurant_path(restaurant), class: "button" do
              %span.icon.is-small
                %i.far.fa-edit
            = link_to restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" do
              %span.icon.is-small
                %i.far.fa-trash-alt

app/views/restaurants/new.html.haml
%h1.title New Restaurant

= render 'form'

app/views/restaurants/show.html.haml
%h1.title= @restaurant.name

.field.is-grouped
  .buttons.are-small
    = link_to 'Edit Restaurant', edit_restaurant_path(@restaurant), class: 'button'
    = link_to 'Back to List', restaurants_path, class: 'button'

%hr

%h2.title.is-4 Menu Items

.field
  = link_to 'New Menu Item', new_restaurant_menu_item_path(@restaurant), class: "button is-link"

%table.table.is-striped.is-fullwidth
  %thead
    %tr
      %th Name
      %th= MenuItem.human_attribute_name("price")
      %th Tag
      %th Actions

  %tbody
    - @menu_items.each do |menu_item|
      %tr
        %td= menu_item.name
        %td= humanized_money_with_symbol menu_item.price
        %td= menu_item.tag.name
        %td
          %p.buttons
            = link_to edit_restaurant_menu_item_path(@restaurant, menu_item), class: "button" do
              %span.icon.is-small
                %i.far.fa-edit
            = link_to restaurant_menu_item_path(@restaurant, menu_item), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" do
              %span.icon
                %i.far.fa-trash-alt